### ISSUE TITLE
pls help 

### ISSUE THREAD

**Issue by avantre** [Avnsx/EFT_Flea_Market_Bot#11]
[LOG:] Bought 5ad5d64486f774079b080af8 [ Key_Shopping_Mall_pharmacy ] at 45000 / 60750
  Waited 0.07870991706848145 Seconds before purchase
   Purchase Success ... ADDED ITEM
    | Stonks: + 15,750 ₽ |
[10:27:03] Balance: 2,071,274 ₽

[LOG:] Bought 5780cf942459777df90dcb72 [ Room 214 Key ] at 23500 / 31500
  Waited 0.19077714681625366 Seconds before purchase
   Purchase Success ... ADDED ITEM
    | Stonks: + 8,000 ₽ |
[10:27:07] Balance: 2,072,974 ₽

[LOG:] Bought 5c052fb986f7746b2101e909 [ Item_barter_electr_rfidreader ] at 26666 / 36000
   Purchase Success ... ADDED ITEM
    | Stonks: + 9,334 ₽ |
[10:27:14] Balance: 2,075,108 ₽

[LOG:] Bought 5d1b304286f774253763a528 [ item_barter_electr_lcd_Clean ] at 21420 / 28500
  Waited 0.45224484205245974 Seconds before purchase

[LOG:] Bought 5c0e533786f7747fa23f4d47 [ Загустин ] at 14111 / 19350
  Waited 0.4721504497528076 Seconds before purchase

[LOG:] Bought 5900b89686f7744e704a8747 [ Woods Plan ] at 6000 / 9539

it works for the first 5-10 seconds then it goes like this

[LOG:] Bought 590c5a7286f7747884343aea [ Gunpowder ] at 7000 / 10500
  Waited 0.20790847778320312 Seconds before purchase

[LOG:] Bought 59e361e886f774176c10a2a5 [ h2o2 ] at 6000 / 9126
  Waited 0.5606361937522888 Seconds before purchase

[INFO:] Next Iteration with token: 0c8f16ac4c871f3a0c6656d7d8f15fb2
     Wishlist currently includes: 317 items!

[LOG:] Bought 5c052e6986f7746b207bc3c9 [ Item_barter_medical_defibrillator ] at 133000 / 168450
  Waited 0.5105698466300964 Seconds before purchase

[LOG:] Bought 5bc9bdb8d4351e003562b8a1 [ item_barter_valuable_elibadge ] at 34000 / 45217
  Waited 0.39414013862609865 Seconds before purchase

[LOG:] Bought 5bc9bdb8d4351e003562b8a1 [ item_barter_valuable_elibadge ] at 34500 / 45217

[LOG:] Bought 5c052fb986f7746b2101e909 [ Item_barter_electr_rfidreader ] at 27000 / 36000

[LOG:] Bought 5734758f24597738025ee253 [ Golden neck chain ] at 21000 / 28632
  Waited 0.44731056213378906 Seconds before purchase

[LOG:] Bought 5780d0532459777a5108b9a2 [ Office key ] at 5000 / 8330
  Waited 0.12804024934768676 Seconds before purchase

[LOG:] Bought 5900b89686f7744e704a8747 [ Woods Plan ] at 6000 / 9539

**Comment by avantre** [comment]
> [LOG:] Bought 5ad5d64486f774079b080af8 [ Key_Shopping_Mall_pharmacy ] at 45000 / 60750
> Waited 0.07870991706848145 Seconds before purchase
> Purchase Success ... ADDED ITEM
> | Stonks: + 15,750 ₽ |
> [10:27:03] Balance: 2,071,274 ₽
> 
> [LOG:] Bought 5780cf942459777df90dcb72 [ Room 214 Key ] at 23500 / 31500
> Waited 0.19077714681625366 Seconds before purchase
> Purchase Success ... ADDED ITEM
> | Stonks: + 8,000 ₽ |
> [10:27:07] Balance: 2,072,974 ₽
> 
> [LOG:] Bought 5c052fb986f7746b2101e909 [ Item_barter_electr_rfidreader ] at 26666 / 36000
> Purchase Success ... ADDED ITEM
> | Stonks: + 9,334 ₽ |
> [10:27:14] Balance: 2,075,108 ₽
> 
> [LOG:] Bought 5d1b304286f774253763a528 [ item_barter_electr_lcd_Clean ] at 21420 / 28500
> Waited 0.45224484205245974 Seconds before purchase
> 
> [LOG:] Bought 5c0e533786f7747fa23f4d47 [ Загустин ] at 14111 / 19350
> Waited 0.4721504497528076 Seconds before purchase
> 
> [LOG:] Bought 5900b89686f7744e704a8747 [ Woods Plan ] at 6000 / 9539
> 
> **it works for the first 5-10 seconds then it goes like this**
> 
> [LOG:] Bought 590c5a7286f7747884343aea [ Gunpowder ] at 7000 / 10500
> Waited 0.20790847778320312 Seconds before purchase
> 
> [LOG:] Bought 59e361e886f774176c10a2a5 [ h2o2 ] at 6000 / 9126
> Waited 0.5606361937522888 Seconds before purchase
> 
> [INFO:] Next Iteration with token: 0c8f16ac4c871f3a0c6656d7d8f15fb2
> Wishlist currently includes: 317 items!
> 
> [LOG:] Bought 5c052e6986f7746b207bc3c9 [ Item_barter_medical_defibrillator ] at 133000 / 168450
> Waited 0.5105698466300964 Seconds before purchase
> 
> [LOG:] Bought 5bc9bdb8d4351e003562b8a1 [ item_barter_valuable_elibadge ] at 34000 / 45217
> Waited 0.39414013862609865 Seconds before purchase
> 
> [LOG:] Bought 5bc9bdb8d4351e003562b8a1 [ item_barter_valuable_elibadge ] at 34500 / 45217
> 
> [LOG:] Bought 5c052fb986f7746b2101e909 [ Item_barter_electr_rfidreader ] at 27000 / 36000
> 
> [LOG:] Bought 5734758f24597738025ee253 [ Golden neck chain ] at 21000 / 28632
> Waited 0.44731056213378906 Seconds before purchase
> 
> [LOG:] Bought 5780d0532459777a5108b9a2 [ Office key ] at 5000 / 8330
> Waited 0.12804024934768676 Seconds before purchase
> 
> [LOG:] Bought 5900b89686f7744e704a8747 [ Woods Plan ] at 6000 / 9539

**Comment by avantre** [comment]
it works for the first 5-10 seconds then it goes like this

**Comment by Avnsx** [comment]
dublicate of https://github.com/Avnsx/EFT_Flea_Market_Bot/issues/10
