### ISSUE TITLE
Add me! Also I wanna help you! - Null#6235

### ISSUE THREAD

**Issue by Anonymoushacker4926** [Avnsx/EFT_Flea_Market_Bot#14]
I added you on discord, also I wanna help you code it better and update it with you. Null#6235 - I wanna make it look nice etc. I've been experimenting with it making it look better you know. Alright, just hit me up whenever if you want. Btw I don't fully know how to code, but I've done it enough to understand mostly what's going on and code shit etc.

**Comment by Avnsx** [comment]
Sorry I decided not to update it for now. I've moved on to other projects, which appeal more interesting to me.
