### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by Niker19** [Avnsx/EFT_Flea_Market_Bot#2]
When the exe is executed it causes the game launcher to open. However, when the game is launched it crashes, thank you for your time.

**Comment by Avnsx** [comment]
I need a propper error output, also what exe are you talking about?

Can you open source.py with Idle and build it there?

How to:
Windows Search > Type in Idle > open idle
Inside Idle > Click on File (top left side) > Open > select source.py from your install location > Now either go to Run and press Run Module or just press F5 > In the new window it should show the error that causes it to crash.

Respond here with the error!

**Comment by Niker19** [comment]
Traceback (most recent call last):
  File "F:\Downloads\EFT_Flea_Market_Bot-master\source.py", line 449, in <module>
    PHPSESSID = token.getToken()
  File "F:\Downloads\EFT_Flea_Market_Bot-master\getToken.py", line 45, in getToken
    subprocess.Popen(command_tarkov, stdout=DEVNULL, stderr=DEVNULL)
UnboundLocalError: local variable 'command_tarkov' referenced before assignment
>>>

**Comment by Avnsx** [comment]
Delete the old folder and download the new version I just published!

**Comment by Avnsx** [comment]
> Traceback (most recent call last):
> File "F:\Downloads\EFT_Flea_Market_Bot-master\source.py", line 449, in
> PHPSESSID = token.getToken()
> File "F:\Downloads\EFT_Flea_Market_Bot-master\getToken.py", line 45, in getToken
> subprocess.Popen(command_tarkov, stdout=DEVNULL, stderr=DEVNULL)
> UnboundLocalError: local variable 'command_tarkov' referenced before assignment
> 
> > > >

Does it work now ?

**Comment by Niker19** [comment]
Checking now

**Comment by Niker19** [comment]
It seems to be working now appreciate the help 😄
