### ISSUE TITLE
Error i get when starting the client

### ISSUE THREAD

**Issue by UniqueWolf** [Avnsx/EFT_Flea_Market_Bot#3]
[INFO:] Welcome to Developer Version 0.3 for Game Client Version 0.12.6.8026 on Unity Engine Version 2018.4.13f1
[INFO:] This github fork was developed by Avn @ unknowncheats. Additionaly huge thanks to yagamiraku & astron4ik!
[INFO:] The last manual update to this code was on 07/01/2020 by Avn unknowncheats.me/forum/members/2564688.html
[LOG:] Loaded List: Wishlist
[LOG:] Loaded List: Complete Entry
[LOG:] Launching and waiting for the Escape from Tarkov Client...

[INFO:] Starting with token:
[14:44:51] Balance: 0 ₽
Traceback (most recent call last):
  File "C:\Users\joe\Desktop\EFT_Flea_Market_Bot-master\EFT_Flea_Market_Bot-master\source.py", line 468, in <module>
    for trader in traders_list:
TypeError: 'NoneType' object is not iterable

**Comment by Avnsx** [comment]
This error should not even happen, this occurs if the Tarkov server does not respond with a valid trader response. This happens completly randomly, when the server is under heavy use, you have a not compatible OS or you fucked up installation. I would recommend you trying later again as this is something temporary. If this doesn't fix itsself by tmrw hmu on this again and I'll give you an edited source with an bypass to this issue
