### ISSUE TITLE
Bot loses money 

### ISSUE THREAD

**Issue by Blind444** [Avnsx/EFT_Flea_Market_Bot#5]
The Bot loses money ,instead of making money?

**Comment by Niker19** [comment]
Same issue https://github.com/Avnsx/EFT_Flea_Market_Bot/issues/4 , please close this issue there is no reason to have multiple forms for the same issue.

**Comment by Avnsx** [comment]
dublicate https://github.com/Avnsx/EFT_Flea_Market_Bot/issues/4
