### ISSUE TITLE
Bot no work 

### ISSUE THREAD

**Issue by avantre** [Avnsx/EFT_Flea_Market_Bot#7]
Now such a mistake, I open it immediately closes

Traceback (last call was last):
File "C: \ EFT_Flea_Market_Bot-master \ source.py", line 281, in <module>
subprocess.Popen (startlauncher)
File "C: \ Program Files (x86) \ Python38-32 \ lib \ subprocess.py", line 854, in __init__
self._execute_child (args, executable, preexec_fn, close_fds,
File "C: \ Program Files (x86) \ Python38-32 \ lib \ subprocess.py", line 1307, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess (executable file, arguments,
OSError: [WinError 740]

**Comment by Avnsx** [comment]
Make sure to execute either EFT and the bot with Admin mode or disable Admin mode for both by going into their properties > launch as admin > untick.

It's either that or you're using a unsupported operational system, or a 32-bit version with 64-bit python & 64-bit winapi.

**Comment by avantre** [comment]
everything is done, downloaded the 64 bit version, still the same error

**Comment by avantre** [comment]
sorry for english, I'm from Russia

**Comment by avantre** [comment]
maybe it requires administrator rights?

**Comment by avantre** [comment]
python tells me that surgery requires an increase

**Comment by avantre** [comment]
Traceback (most recent call last):
  File "C:\EFT_Flea_Market_Bot-master\source.py", line 281, in <module>
    subprocess.Popen(startlauncher)
  File "C:\Program Files\Pyrhon\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Pyrhon\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 740] Запрошенная операция требует повышения

**Comment by avantre** [comment]
I reinstalled everything, python x64, pywin32 also x64

**Comment by avantre** [comment]
windows x64 too

**Comment by Avnsx** [comment]
`[WinError 740] Запрошенная операция требует повышения` 
= WINDOWS ERROR 740: THE REQUIRED PROCESS NEEDS ELEVATED ACCESS
= start it as administrator, also start cmd as administrator when installing pip commands incase you haven't
