### ISSUE TITLE
Losing Money + Added Item Gone

### ISSUE THREAD

**Issue by dontletdaddyknow** [Avnsx/EFT_Flea_Market_Bot#8]
Seems that purchasing items only loses main balance. Haven't had a item that made me money so far.
Also, there seems to be a bug that after 30 seconds, it stops actually buying the items since the "Added Item" notification is gone. This is on Windows 10 ver 1909

[LOG:] Bought 5c1e2a1e86f77431ea0ea84c [ item_lab_glass_office ] at 88000 / 93465
  Waited 0.4769145178794861 Seconds before purchase
   Purchase Success ... ADDED ITEM
    | Stonks: + 5,465 ₽ |
[19:54:25] Balance: 2,765,343 ₽

[LOG:] Bought 5c1e2a1e86f77431ea0ea84c [ item_lab_glass_office ] at 89500 / 93465
   Purchase Success ... ADDED ITEM
    | Stonks: + 3,965 ₽ |
[19:54:26] Balance: 2,675,843 ₽

[LOG:] Bought 5c1e2a1e86f77431ea0ea84c [ item_lab_glass_office ] at 90000 / 93465
   Purchase Success ... ADDED ITEM
    | Stonks: + 3,465 ₽ |
[19:54:26] Balance: 2,735,387 ₽

[LOG:] Bought 5a1452ee86f7746f33111763 [ San 222 Key ] at 77700 / 79222
   Purchase Success ... ADDED ITEM
    | Stonks: + 1,522 ₽ |
[19:54:27] Balance: 2,721,065 ₽

**Comment by Avnsx** [comment]
dublicate of https://github.com/Avnsx/EFT_Flea_Market_Bot/issues/4
