### ISSUE TITLE
ERROR 1500

### ISSUE THREAD

**Issue by xHypn13245** [Avnsx/EFT_Flea_Market_Bot#9]
Everytime i run the bot it attempts to purchase a item but just gives "[LOG:] Bought 5ad7217186f7746744498875 [ Key_cash_machine_OLI ] at 45000 / 60000
  Waited 0.44726455211639404 Seconds before purchase
[ERROR:] 1500"

**Comment by Avnsx** [comment]
This error equals when the shitty developed BSG server, can't respond in time due to heavy traffic. I've updated the source patching this error, delete and re-download.
